# Minimal Light academic homepage
remote_theme: yaoyao-liu/minimal-light

title: Yitong Qiu
position: Incoming Ph.D. Student
affiliation: Columbia University IEOR
affiliation_link: https://ieor.columbia.edu/
email: yq2463 (at) columbia.edu

keywords: theoretical machine learning, diffusion models, reinforcement learning, applied probability
description: Academic homepage of Yitong Qiu, an incoming Ph.D. student in Industrial Engineering and Operations Research at Columbia University.
canonical: https://creepierchunk37.github.io/

github_link: https://github.com/CreepierChunk37
avatar: https://avatars.githubusercontent.com/u/130744956?v=4

enable_footnote: true
auto_dark_mode: true
font: "Sans Serif"

exclude:
  - README.md
  - LICENSE
